packages:
  - 'packages/codebase'
  - 'packages/__tests__/implementation'
  - 'packages/__tests__/real-implementation'

allowBuilds:
  esbuild: true

nodeLinker: hoisted

minimumReleaseAgeExclude:
  - '@bemedev/*'
